In [1]:
from chemicals import CAS_from_any, Tb
import chemicals.critical as ct
import chemicals.phase_change
import chemicals.data_reader as cd
import chemicals

In [2]:
chemicals.vapor_pressure.Psat_data_Perrys2_8

,Chemical,C1,C2,C3,C4,C5,Tmin,Tmax
CAS,,,,,,,,
50-00-0,Formaldehyde,101.510,-4917.20,-13.7650,2.203100e-02,1.0,181.15,408.00
55-21-0,Benzamide,85.474,-11932.00,-8.3348,1.285000e-18,6.0,403.00,824.00
56-23-5,Carbon tetrachloride,78.441,-6128.10,-8.5766,6.846500e-06,2.0,250.33,556.35
57-55-6,"1,2-Propylene glycol",212.800,-15420.00,-28.1090,2.156400e-05,2.0,213.15,626.00
60-29-7,Diethyl ether,136.900,-6954.30,-19.2540,2.450800e-02,1.0,156.85,466.70
...,...,...,...,...,...,...,...,...
10028-15-6,Ozone,40.067,-2204.80,-2.9351,7.752000e-16,6.0,80.15,261.00
10035-10-6,Hydrogen bromide,29.315,-2424.50,-1.1354,2.380600e-18,6.0,185.15,363.15
10102-43-9,Nitric oxide,72.974,-2650.00,-8.2610,9.700000e-15,6.0,109.50,180.15
13511-13-2,Propenylcyclohexene,64.268,-7298.90,-5.9109,4.848200e-18,6.0,199.00,636.00
132259-10-0,Air,21.662,-692.39,-0.3920,4.757400e-03,1.0,59.15,132.45

In [3]:
def showdf(df):
    print(df.shape)
    return df.head()

# ABC

In [9]:
df1 = chemicals.vapor_pressure.Psat_data_Landolt_Antoine
#df1_1 = df1.copy()
#df1_1["Psat"] = df1_1["A"]-(df1_1["B"]/(df1_1["C"]))
showdf(df1)
#df1.to_csv("Psat_raw1.csv")

(6346, 6)

,Name,A,B,C,Tmin,Tmax
CAS,,,,,,
50-00-0,Methanal,21.370292,2204.126554,-30.150,190.0,271.0
51-66-1,p-Methoxy-acetanilide,20.273433,3916.190674,-177.100,456.0,533.0
51-75-2,N-Methylbis(2-chloroethyl)amine,25.609075,6563.288549,0.000,273.0,333.0
51-79-6,Urethane,23.846838,5018.000667,-49.920,338.0,457.0
51-80-9,"N,N,Nâ€™,Nâ€™-Tetramethyl-methane diamine",19.583348,2251.525269,-77.911,273.0,348.0

In [5]:
df2 = chemicals.vapor_pressure.Psat_data_AntoinePoling
showdf(df2)
#df2.to_csv("Psat_raw2.csv")

(325, 6)

                    Chemical         A         B       C    Tmin    Tmax
CAS
56-23-5  tetrachloromethane    9.10445  1265.632 -41.002  259.00  373.76
60-29-7       diethyl ether    9.10962  1090.640 -41.950  229.71  328.31
62-53-3        benzeneamine    9.40870  1692.770 -72.710  349.86  484.81
64-17-5             ethanol   10.33675  1648.220 -42.232  276.50  369.54
64-19-7       ethanoic acid    9.54456  1555.120 -48.500  297.58  414.97

# ABCD

In [13]:
df3 = chemicals.vapor_pressure.Psat_data_VDI_PPDS_3
showdf(df3)

(275, 8)

,Chemical,Tm,Tc,Pc,A,B,C,D
CAS,,,,,,,,
50-00-0,Formaldehyde,181.15,408.05,6590000.0,-7.46907,1.28290,-0.50464,-4.29089
56-23-5,Carbon tetrachloride,250.25,556.35,4560000.0,-7.11728,1.96174,-2.05900,-3.26771
56-81-5,Glycerol,291.45,850.05,7500000.0,-6.94758,-0.33345,-5.98569,-1.33011
60-29-7,Diethyl ether,156.75,466.63,3651000.0,-7.55709,2.15613,-3.02766,-2.37858
62-53-3,Aniline,267.15,699.05,5310000.0,-7.86006,1.96206,-3.65571,-2.00622

In [15]:
df4 = chemicals.vapor_pressure.Psat_data_WagnerMcGarry
showdf(df4)

(245, 8)

,Name,A,B,C,D,Pc,Tc,Tmin
CAS,,,,,,,,
50-00-0,formaldehyde,-7.29343,1.083950,-1.63882,-2.30677,6586100.0,408.00,184.0
56-23-5,carbon tetrachloride,-7.07139,1.714970,-2.89930,-2.49466,4550780.0,556.40,250.0
60-29-7,diethylether,-7.29916,1.248280,-2.91931,-3.36740,3646100.0,466.74,250.0
62-53-3,aniline,-7.65517,0.853858,-2.51602,-5.96795,5309400.0,699.00,376.0
64-17-5,ethanol,-8.51838,0.341626,-5.73683,8.32581,6130870.0,513.92,293.0

In [16]:
df5 = chemicals.vapor_pressure.Psat_data_WagnerPoling
showdf(df5)

(104, 9)

,Name,A,B,C,D,Tc,Pc,Tmin,Tmax
CAS,,,,,,,,,
60-29-7,diethyl ether,-7.43301,1.78847,-2.47930,-3.28110,466.74,3650000.0,156.85,466.74
64-17-5,ethanol,-8.68587,1.17831,-4.87620,1.58800,513.92,6132000.0,159.05,513.92
64-18-6,methanoic acid,-7.24917,0.44255,-0.35558,-0.96906,588.00,5807000.0,281.45,588.00
64-19-7,ethanoic acid,-8.29430,0.97928,-0.21745,-5.72367,592.71,5786000.0,289.81,592.71
67-56-1,methanol,-8.63571,1.17982,-2.47900,-1.02400,512.64,8092000.0,175.47,512.64

# ABC